### ISSUE TITLE
Uncaught TypeError: Cannot read property 'en' of undefined

### ISSUE THREAD

**Issue by hawkrdg** [bus-stop/x-terminal#185]
[Enter steps to reproduce:]

1. install x-terminal plugin
2. try typing anything - in this case 'en'

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.1
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 11.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'en' of undefined

```
At /home/cliff/.atom/packages/x-terminal/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js:9

TypeError: Cannot read property 'en' of undefined
    at Object.name (/packages/x-terminal/node_modules/font-finder/dist/extract.js:33:36)
    at getMetadata (/packages/x-terminal/node_modules/font-finder/dist/index.js:87:23)
    at /packages/x-terminal/node_modules/font-finder/dist/index.js:31:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:107:22)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
    at wrapper (/packages/x-terminal/node_modules/font-finder/dist/index.js:109:13)
```

### Commands

```
     -0:17.5.0 x-terminal:open (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
color-picker 2.3.0 
html-tag-auto-complete 2.0.0 
intentions 1.1.5 
linter 3.1.1 
linter-json-lint 0.1.3 
linter-ui-default 2.1.2 
multi-cursor 3.0.0 
open-in-browsers 0.0.30 
script 3.26.0 
Stylus 3.2.0 
x-terminal 11.0.2 
```

**Comment by UziTech** [comment]
Does this continue to happen once Atom is restarted?

**Comment by the-j0k3r** [comment]
FYI this is one of the reasons why this addon should be optional and disabled if webgl is on to avoid all these issues with beta addons.

Also including some ligature fonts may yeid a better OOTB UX

**Comment by UziTech** [comment]
If we create a checkbox to disable every part of xterm that could break, we would need a lot of checkboxes. And there is no indication this has anything to do with webgl.

**Comment by UziTech** [comment]
> Also including some ligature fonts may yeid a better OOTB UX

I don't think bundling fonts is in the scope of this package. If the user wants ligatures they can download a font that allows them.

**Comment by the-j0k3r** [comment]
> I don't think bundling fonts is in the scope of this package. If the user wants ligatures they can download a font that allows them.

We should add it to readme Fira code and Cascadia Code maybe others that are of sufficient quality.

> If we create a checkbox to disable every part of xterm that could break, we would need a lot of checkboxes. And there is no indication this has anything to do with webgl.

If I understand you correctly, you are equating 1 checkbox (to what I see as empowering users to make a choice based on their needs), to some scenario thats is unreasonable UX design.
Seems our reasoning is incompatible, yet again, =)

**Comment by UziTech** [comment]
Users can already make that choice with the font setting. The way the user turns off ligatures right now is to use a font that doesn't support ligatures. A checkbox for that choice would be redundant.

**Comment by UziTech** [comment]
I'm going to close this since there has been no response from the OP and it is not reproducible. If you have more information that might help us fix this feel free to reopen it and provide more information on how to reproduce or fix it.
