### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 74. Received 78

### ISSUE THREAD

**Issue by ghost** [bus-stop/x-terminal#223]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.10
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 11.0.5

### Stack Trace

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= 74. Received 78

```
At /home/radulucian1975/.atom/packages/x-terminal/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js:9

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 74. Received 78
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readUInt32BE (internal/buffer.js:296:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/os2.js:52:37)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:95:65
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### Commands

```
 14x -9:52.7.0 core:backspace (input.hidden-input)
     -9:36.1.0 settings-view:view-installed-packages (input.hidden-input)
     -9:28.8.0 core:confirm (input.hidden-input)
  8x -5:45.2.0 core:backspace (input.hidden-input)
  3x -5:17.3.0 core:confirm (input.hidden-input)
  3x -2:31.7.0 core:backspace (input.hidden-input)
  3x -2:28.6.0 core:confirm (input.hidden-input)
  4x -2:14.6.0 core:move-left (input.hidden-input)
     -2:13.6.0 core:backspace (input.hidden-input)
     -2:12.4.0 core:confirm (input.hidden-input)
     -0:44.1.0 nuclide-refactorizer:refactorize (input.hidden-input)
     -0:31.5.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -0:23.5.0 github:open-reviews-tab (input.hidden-input)
     -0:15.5.0 x-terminal:focus (div.highlights)
```

### Non-Core Packages

```
000-project-shell-env 0.3.0 
atom-bash 1.1.1 
Atom-Bash-Snippets 0.0.3 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-shell-commands 1.5.0 
atom-terminal-powershell 1.1.0 
autocomplete-bash-builtins 0.3.5 
bash-bang-syntax 0.3.0 
command-executor 1.4.3 
concourse-pipeline-yaml 1.13.0 
dqs-shell-commands 2.2.4 
elias-comments 1.1.0 
env-from-shell 0.3.0 
format-shell 2.2.1 
Hydrogen 2.14.6 
ide-bash 1.0.11 
ide-yml 0.7.8-0 
inter-dimensional-syntax 2.0.0 
language-habitat 0.3.0 
language-unix-shell 0.40.1 
linter-checkbashisms 0.1.5 
linter-shellcheck 1.6.0 
linter-spell-shellscript 0.2.0 
on-save 2.2.1 
open-bash-git 2.3.3 
open-shell-active-directory 2.3.2 
quantum-shell 0.7.1 
save-commands 0.6.11 
script 3.26.0 
set-syntax 0.4.0 
set-syntax-emacs 0.1.0 
shell-it 0.5.0 
splash-ui 0.4.0 
teletype 0.13.4 
TerminalColor 1.1.0 
tool-bar-basic-git 0.4.0 
x-terminal 11.0.5 
```

**Comment by the-j0k3r** [comment]
These ligatures addon issues are a dime a dozen.
