### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focusOnTerminal' of undefined

### ISSUE THREAD

**Issue by jaimin1618** [bus-stop/x-terminal#289]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 13.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'focusOnTerminal' of undefined

```
At C:\Users\JAIMIN CHOKHAWALA\.atom\packages\x-terminal\src\x-terminal.js:636

TypeError: Cannot read property 'focusOnTerminal' of undefined
    at XTerminalSingleton.focus (/packages/x-terminal/src/x-terminal.js:636:19)
    at HTMLElement.xTerminalFocus (/packages/x-terminal/src/x-terminal.js:213:36)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:351740)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:350215)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:1:833422)
    at EventEmitter.t (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:1:841476)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -1:50.4.0 core:save (input.hidden-input)
     -1:40.1.0 x-terminal:open-split-up-context-menu (div.title)
     -1:13.9.0 editor:newline (input.hidden-input)
     -1:13.1.0 core:backspace (input.hidden-input)
     -1:12 autocomplete-plus:confirm (input.hidden-input)
  2x -1:10.7.0 core:save (input.hidden-input)
     -0:59.3.0 core:backspace (input.hidden-input)
  2x -0:58.3.0 core:save (input.hidden-input)
  9x -0:48.2.0 core:backspace (input.hidden-input)
     -0:46.3.0 core:save (input.hidden-input)
     -0:32.2.0 editor:newline (input.hidden-input)
  2x -0:31.2.0 core:backspace (input.hidden-input)
     -0:28.1.0 core:cut (input.hidden-input)
  2x -0:27.7.0 core:save (input.hidden-input)
     -0:20.8.0 core:close (textarea.xterm-helper-textarea)
     -0:11.7.0 x-terminal:focus (div.title)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
flex-monokai 0.0.5 
kite 0.204.0 
monokai 0.27.0 
monokai-shade 0.4.0 
x-terminal 13.0.3 
```

**Comment by UziTech** [comment]
What are the steps to reproduce this error?

**Comment by UziTech** [comment]
Looks like the error is thrown in this function:

https://github.com/bus-stop/x-terminal/blob/8993450f906a019e892f9a5b07907f4534ff61e1/src/x-terminal.js#L631-L638

If there are terminals open there should always be one with `activeIndex === 0`.

We could just silence the error and open a new terminal but I would rather figure out why it is erroring.

**Comment by the-j0k3r** [comment]
>but I would rather figure out why it is erroring.

Usually its due to bad updates/upgrades so my goto troubleshoot is 

1. Close Atom (all instances)
1. Remove/delete `~/.atom/packages/x-terminal`
1. run on an external terminal `apm install x-terminal`
1. Open Atom profit
1. Open terminal

**Comment by UziTech** [comment]
closing as stale
