### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loadCell' of undefined

### ISSUE THREAD

**Issue by rodrigomaldonadov** [bus-stop/x-terminal#359]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 13.0.16

### Stack Trace

Uncaught TypeError: Cannot read property 'loadCell' of undefined

```
At C:\Users\rodri\.atom\packages\x-terminal\node_modules\xterm\lib\xterm.js:1

TypeError: Cannot read property 'loadCell' of undefined
    at t._forEachCell (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:122862)
    at t._drawBackground (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:123340)
    at t.onGridChanged (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:125037)
    at t.renderRows (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:116513)
    at t._renderRows (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:162886)
    at e._renderCallback (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:160911)
    at e._innerRefresh (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:37083)
    at /packages/x-terminal/node_modules/xterm/lib/xterm.js:1:36799
```

### Commands

```
     -0:10 x-terminal:open (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-live-server 2.3.0 
b-bootstrap-autocomplete 0.4.6 
busy-signal 2.0.1 
emmet 2.4.3 
ide-rust undefined 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
reload-button 0.1.0 
rust-lang 0.6.0 
x-terminal 13.0.16 
```

**Comment by the-j0k3r** [comment]
Bad install or upgrade, the gremlins, =)

1. Close Atom (all instances)
1. Remove `~/.atom/packages/x-terminal`
1. run on an external terminal `apm install x-terminal`
1. Open Atom profit

This should be the goto default action before reporting these issues.

**Comment by the-j0k3r** [comment]
I think its time to close this now, the solution is what I previously mentioned.
