### ISSUE TITLE
[BR] Installation Failed

### ISSUE THREAD

**Issue by zhaolinlau** [bus-stop/x-terminal#523]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Steps to reproduce

1. type apm install x-terminal
2. press enter

**Expected behavior:**
Installing minimap to C:\Users\Win10\.pulsar\packages done

**Actual behavior:**
Installing x-terminal to C:\Users\Win10\.pulsar\packages failed

```
> node-pty-prebuilt-multiarch@0.10.0 install C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\node_modules\x-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\node_modules\x-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Win10\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Users\\Win10\\AppData\\Local\\Programs\\pulsar\\resources\\app\\ppm\\bin\\node.exe" "C:\\Users\\Win10\\AppData\\Local\\Programs\\pulsar\\resources\\app\\ppm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\node_modules\x-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Win10\AppData\Local\Temp\apm-install-dir-20221127-11076-18kod9.ens8a\package.json'
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No description
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No repository field.
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No README data
npm WARN apm-install-dir-20221127-11076-18kod9.ens8a No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.10.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Win10\.pulsar\.apm\_logs\2022-12-27T03_32_23_890Z-debug.log
```

**Reproduces how often:**
100%

### Versions

```
PS C:\Users\Win10> pulsar --version
PS C:\Users\Win10>
Pulsar  : 1.100.0-beta
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0

```

```
PS C:\Users\Win10> apm --version
apm  2.7.0
npm  6.14.9
node 16.0.0 x64
atom 1.100.0-beta
python 3.10.9
git 2.38.1.windows.1
visual studio

```
OS name and version: Windows 11 22H2
Terminal version: PowerShell 7.3.1

### Additional context
![image](https://user-images.githubusercontent.com/68846168/209607478-f69ba105-05b7-47a0-a9b1-9b012b5041a6.png)

**Comment by wwWT000** [comment]
> 

I also have this issue. I hope the owner of this repository will come and take a look at this issue.

**Comment by UziTech** [comment]
I believe you should be using `ppm` instead of `apm` for pulsar packages. Also this package hasn't been tested with pulsar. If someone wants to create a PR that changes the tests to use pulsar that would be much appreciated 😁👍. It is on my TODO list but it will take a while.

**Comment by tobyink** [comment]
@UziTech I've been using this plugin with PulsarEdit for a few days and it seems okay so far.

**Comment by zhaolinlau** [comment]
> @UziTech I've been using this plugin with PulsarEdit for a few days and it seems okay so far.

How did you install?

**Comment by tobyink** [comment]
I cheated:

```shell
cp -r ~/.atom ~/.pulsar
cp -r ~/.config/Atom ~/.config/Pulsar
```

**Comment by confused-Techie** [comment]
Also @zhaolinlau in Pulsar's Settings you should be able to install the package just like you would in Atom. The package is on the [Pulsar Package Registry](https://web.pulsar-edit.dev/packages/x-terminal)

**Comment by zhaolinlau** [comment]
> Also @zhaolinlau in Pulsar's Settings you should be able to install the package just like you would in Atom. The package is on the [Pulsar Package Registry](https://web.pulsar-edit.dev/packages/x-terminal)

Same error

**Comment by confused-Techie** [comment]
> > Also @zhaolinlau in Pulsar's Settings you should be able to install the package just like you would in Atom. The package is on the [Pulsar Package Registry](https://web.pulsar-edit.dev/packages/x-terminal)
> 
> Same error

So quick disclaimer I'm not affiliated with this codebase at all, but am a maintainer of Pulsar, that's why I suggested it.

But if you are in fact getting the exact same error as above in Pulsar, you have Visual Studio Code 2022 installed. Pulsar is still doing it's best to update our versions of Node, Electron, NPM and friends.

But what that does mean is they don't recognize such a new Visual Studio Code installation. For Pulsar we would recommend installing the 2019 version.

The reason Pulsar cares about Visual Studio is when you install some native packages they need to be built for each OS, and that's done with a C++ toolchain program installed, which Visual Studio is one.

And apparently this repo is a package that needs to be built on installation.
