### ISSUE TITLE
Failed to activate the x-terminal package

### ISSUE THREAD

**Issue by breismam** [bus-stop/x-terminal#88]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 8.2.1

### Stack Trace

Failed to activate the x-terminal package

```
At Cannot find module 'marked'
Require stack:
- C:\Users\ponch\.atom\packages\x-terminal\src\profile-menu-element.js
- C:\Users\ponch\.atom\packages\x-terminal\src\element.js
- C:\Users\ponch\.atom\packages\x-terminal\src\x-terminal.js
- C:\Users\ponch\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

Error: Cannot find module 'marked'
Require stack:
- C:\Users\ponch\.atom\packages\x-terminal\src\profile-menu-element.js
- C:\Users\ponch\.atom\packages\x-terminal\src\element.js
- C:\Users\ponch\.atom\packages\x-terminal\src\x-terminal.js
- C:\Users\ponch\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/x-terminal/src/profile-menu-element.js:22:55)
    at /packages/x-terminal/src/profile-menu-element.js:501:29)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/x-terminal/src/element.js:30:63)
    at /packages/x-terminal/src/element.js:737:18)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/x-terminal/src/x-terminal.js:26:44)
    at /packages/x-terminal/src/x-terminal.js:598:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
git-plus 8.7.1 
hey-pane 1.2.0 
Hydrogen 2.14.1 
intentions 1.1.5 
linter 2.3.1 
linter-tidy 2.4.0 
linter-ui-default 1.8.1 
x-terminal 8.2.1 
```

**Comment by UziTech** [comment]
Try uninstalling and reinstalling it
